module.exports = {
    type: {
        "1": "Public",
        "2": "Private",
        "3": "Institute",
        "4": "University",
        "5": "College",
        "6": "School",
    },
    new_stream: {
        "1": "Engineering",
        "2": "Technology",
        "3": "Skill Trades",
        "4": "Transportation",
        "5": "Science",
        "6": "Arts",
        "7": "Business",
        "8": "Management",
        "9": "Economics",
        "10": "Administration",
        "11": "Law",
        "12": "Politics",
        "13": "Community Services",
        "14": "Education",
        "15": "English For Academic Studies",
        "16": "Health Sciences",
        "17": "Medicine",
        "18": "Nursing",
        "19": "Paramedic",
        "20": "Accounting",
        "21": "Design and Media",
    },
    program_level: {
        "1": "Undergraduate",
        "2": "Graduate",
        "3": "Postgraduate",
        "4": "Secondary",
        "5": "Master",
        "6": "Diploma",
        "7": "Advanced Diploma",
        "8": "Certificate",
        "9": "Bachelor",
        "10": "Degree",
    }
}

